global:
    listen_host: &global_listen_host localhost
    public_host: &global_public_host localhost
    max_connections: &global_max_connections 10
    enable_all: &enable_all True

cms:
    debug: False
    listen_host: *global_listen_host
    listen_port: 80
    workers: default

servers:
    auth:
        listen_port: 1001
        listen_host: *global_listen_host
        public_port: 1001
        public_host: *global_public_host
        max_connections: *global_max_connections
        enabled: *enable_all

    chat:
        listen_port: 2001
        listen_host: *global_listen_host
        public_port: 2001
        public_host: *global_public_host
        max_connections: *global_max_connections
        enabled: *enable_all

    char:
        listen_port: 2002
        listen_host: *global_listen_host
        public_port: 2002
        public_host: *global_public_host
        max_connections: *global_max_connections
        enabled: *enable_all

    venture_explorer:
        listen_port: 2003
        listen_host: *global_listen_host
        public_port: 2003
        public_host: *global_public_host
        max_connections: *global_max_connections
        enabled: *enable_all
